language: php

php:
  - 7.2.13

services:
  - postgresql

before_script:
  - cp .env.travis .env
  - psql -c 'create database mydiary_test;' -U postgres
  - composer self-update
  - composer install --no-interaction

cache:
  directories:
    - node_modules
    - vendor

script:
  - vendor/bin/phpunit
