language: php

php:
  - 7.2

before_script:
  # - cp .env.travis .env
  # - pgsql -e 'create database myDiary_test;'
  # - composer self-update
  - composer install --no-interaction

cache:
  directories:
    - node_modules
    - vendor

script:
  - vendor/bin/phpunit
